AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'S3-github'
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
Outputs:
  BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref MyS3Bucket
