AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  BucketNameParam:
    Type: String
    Description: "The name of the S3 bucket"

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketNameParam
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref MyS3Bucket
